import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import (
    GMAIL_ADDRESS,
    GMAIL_APP_PASSWORD,
    GMAIL_SMTP_PORT,
    GMAIL_SMTP_SERVER,
    EMAIL_RECIPIENT,
)

logger = logging.getLogger(__name__)

CATEGORY_ICONS = {
    "Product Launch": "&#x1F680;",
    "Research": "&#x1F52C;",
    "Business": "&#x1F4BC;",
    "Policy": "&#x2696;&#xFE0F;",
    "Open Source": "&#x1F310;",
    "Analysis": "&#x1F4CA;",
    "Trending": "&#x1F525;",
    "Other": "&#x1F4F0;",
}


def _build_html(digest: list[dict], date_str: str) -> str:
    """Build a clean HTML email body from the digest."""
    stories_html = ""
    for story in digest:
        category = story.get("category", "Other")
        icon = CATEGORY_ICONS.get(category, CATEGORY_ICONS["Other"])

        # Build takeaway bullets
        takeaways = story.get("takeaways", [])
        if not takeaways:
            # Backward compat: fall back to "summary" field if present
            summary = story.get("summary", "")
            takeaways = [summary] if summary else []

        bullets_html = ""
        for bullet in takeaways:
            bullets_html += f"""
                            <tr>
                                <td style="padding: 2px 0; font-size: 13px; color: #444; line-height: 1.4;" valign="top">
                                    <span style="color: #888; margin-right: 6px;">&#x2022;</span>{bullet}
                                </td>
                            </tr>"""

        stories_html += f"""
        <tr>
            <td style="padding: 16px 0; border-bottom: 1px solid #e0e0e0;">
                <div style="font-size: 11px; color: #666; margin-bottom: 4px;">
                    {icon} {category} &middot; {story.get("source", "")}
                </div>
                <a href="{story.get("url", "#")}"
                   style="font-size: 15px; font-weight: 600; color: #1a1a1a; text-decoration: none;">
                    {story.get("title", "Untitled")}
                </a>
                <table width="100%" cellpadding="0" cellspacing="0" style="margin: 6px 0 0 8px;">
                    {bullets_html}
                </table>
            </td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin: 0; padding: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
    <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #f5f5f5; padding: 20px 0;">
        <tr>
            <td align="center">
                <table width="600" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 8px; overflow: hidden;">
                    <tr>
                        <td style="background-color: #1a1a2e; padding: 24px 32px;">
                            <h1 style="margin: 0; color: #ffffff; font-size: 22px; font-weight: 700;">
                                AI News Digest
                            </h1>
                            <p style="margin: 4px 0 0 0; color: #a0a0c0; font-size: 13px;">
                                {date_str} &middot; {len(digest)} stories
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 8px 32px 24px 32px;">
                            <table width="100%" cellpadding="0" cellspacing="0">
                                {stories_html}
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td style="background-color: #f9f9f9; padding: 16px 32px; text-align: center;">
                            <p style="margin: 0; font-size: 12px; color: #999;">
                                Generated by Automation Lab &middot; ai-news-digest
                            </p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>"""
    return html


def send_digest(digest: list[dict], date_str: str) -> bool:
    """Send the digest email via Gmail SMTP. Returns True on success."""
    if not all([GMAIL_ADDRESS, GMAIL_APP_PASSWORD, EMAIL_RECIPIENT]):
        logger.error("Gmail credentials or recipient not set. Cannot send email.")
        return False

    if not digest:
        logger.warning("Empty digest -- not sending email.")
        return False

    html_body = _build_html(digest, date_str)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"AI News Digest -- {date_str}"
    msg["From"] = f"AI News Digest <{GMAIL_ADDRESS}>"
    msg["To"] = EMAIL_RECIPIENT

    plain_text = f"AI News Digest for {date_str}\n\n"
    for story in digest:
        plain_text += f"[{story.get('category', 'Other')}] {story.get('title', 'Untitled')}\n"
        for bullet in story.get("takeaways", []):
            plain_text += f"  - {bullet}\n"
        plain_text += f"  {story.get('url', '')}\n\n"

    msg.attach(MIMEText(plain_text, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP_SSL(GMAIL_SMTP_SERVER, GMAIL_SMTP_PORT) as server:
            server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_ADDRESS, EMAIL_RECIPIENT, msg.as_string())
        logger.info("Digest email sent to %s.", EMAIL_RECIPIENT)
        return True
    except smtplib.SMTPException as e:
        logger.error("Failed to send email: %s", e)
        return False
